# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoSwift3' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoSwift3
  #pod "SwiftDate", :git => 'https://github.com/malcommac/SwiftDate.git', :branch => 'feature/swift-3.0'
  #pod "SwiftDate"
end
